;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-insert-left-brace
	TeX-insert-backslash
	TeX-insert-sub-or-superscript
	avy-goto-char
	backward-sexp
	ess-roxy-move-beginning-of-line
	ess-smart-S-assign
	ess-smart-comma
	ess-yank
	forward-sexp
	icicle-goto-marker-or-set-mark-command
	icicle-yank-maybe-completing
	keyboard-escape-quit
	kill-region
	mark-sexp
	markdown-outdent-or-delete
	next-buffer
	org-beginning-of-line
	org-end-of-line
	org-force-self-insert
	org-self-insert-command
	paredit-backward
	paredit-backward-kill-word
	paredit-forward
	paredit-forward-delete
	paredit-forward-kill-word
	paredit-semicolon
	paredit-wrap-round
	read-only-mode
	scroll-down-line
	skeleton-pair-insert-maybe
	))

(setq mc/cmds-to-run-once
      '(
	ess-r-devtools-load-package
	iedit-switch-to-mc-mode
	wdired-finish-edit
	))
